// src/components/Header.vue
<template>
  <header class="header">
    <h1>todos</h1>
    <input class="new-todo" placeholder="What needs to be done?" autofocus v-model.trim="input" @change="onInputChange">
  </header>
</template>

<script lang="ts">
import { Vue, Component, Emit } from 'vue-property-decorator'

@Component
export default class Header extends Vue {
  private input = ''

  // onInputChange () {
  //   if (!this.input) return
  //   // console.log(this.input)
  //   this.$emit('change', this.input)
  //   this.input = ''
  // }

  @Emit('change')
  onInputChange () {
    if (!this.input) return
    const text = this.input
    this.input = ''
    return text
  }
}
</script>

// src/components/Header.jsx
import React, { Component } from 'react'

class Header extends Component {
  constructor (props) {
    super(props)
    this.state = { value: '' }
    this.handleChange = this.handleChange.bind(this)
    this.handleKeyDown = this.handleKeyDown.bind(this)
  }

  render () {
    return (
      <header className='header'>
        <h1>todos</h1>
        <input
          className='new-todo'
          placeholder='What needs to be done?'
          autoFocus
          value={this.state.value}
          onChange={this.handleChange}
          onKeyDown={this.handleKeyDown} />
      </header>
    )
  }

  handleChange (e) {
    this.setState({ value: e.target.value })
  }

  handleKeyDown (e) {
    if (e.which === 13) {
      this.props.onAdd(e.target.value.trim())
      this.setState({ value: '' })
    }
  }
}

export default Header
